# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://ruterly.com
date_format: "ordinal"
title: TNK
subtitle: "Ruter's Blog"
description: "Ruter 的个人博客"
keywords: Ruter, TNK, Ruter's, technical
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Ruter
organization: SundayStart Studio
organization_url: 
github_username: ruter
location: Shenzhen, China
email: i@ruterly.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: Wiki

  -
    href: /links/
    label: 友链

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: ruter/TNK-Blog

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: ruter
    repo: TNK-Comments
    oauth:
        client_id: dfb2389dad5c72514ed6
        client_secret: b33025a7e7a90226db5c179273970c4b96c7ee96
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: ruter
    repo: TNK-Comments
    clientID: dfb2389dad5c72514ed6
    clientSecret: b33025a7e7a90226db5c179273970c4b96c7ee96
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-117326683-1
